import type { FileChange } from '../git/parse.js';
import { GlobSet } from './glob.js';

export type Verdict = { scaffolding: false } | { scaffolding: true; reason: string };

const NOT: Verdict = { scaffolding: false };
const yes = (reason: string): Verdict => ({ scaffolding: true, reason });

/**
 * Paths that are generated or vendored by convention. Certain enough to act on without
 * looking inside the file.
 */
const VENDORED = new GlobSet([
  'package-lock.json',
  'pnpm-lock.yaml',
  'yarn.lock',
  'npm-shrinkwrap.json',
  'bun.lockb',
  'Cargo.lock',
  'poetry.lock',
  'Pipfile.lock',
  'composer.lock',
  'Gemfile.lock',
  'go.sum',
  '*.lock',
  'vendor/',
  'third_party/',
  'node_modules/',
  'dist/',
  'build/',
  'out/',
  '.angular/',
  '.next/',
  '.nuxt/',
  'coverage/',
  '__snapshots__/',
  '*.min.js',
  '*.min.css',
  '*.map',
  '*.pb.go',
  '*_pb2.py',
  '*.g.dart',
  '*.g.ts',
  '*.generated.ts',
  '*.generated.cs',
  '*.designer.cs',
]);

/**
 * Config files a workspace generator writes and then never asks a human to read. Only
 * treated as scaffolding when the repository actually is such a workspace.
 */
const WORKSPACE_CONFIG = new GlobSet([
  'project.json',
  'jest.config.ts',
  'jest.config.js',
  'jest.preset.js',
  'vite.config.ts',
  'vitest.config.ts',
  '.eslintrc.json',
  '.eslintrc.js',
  'eslint.config.js',
  '.babelrc',
  'tsconfig.json',
  'tsconfig.*.json',
  'karma.conf.js',
  '.browserslistrc',
]);

/** Root registries a generator edits — but so does a person, so these need corroboration. */
const ROOT_REGISTRY = new GlobSet([
  '/nx.json',
  '/tsconfig.base.json',
  '/angular.json',
  '/workspace.json',
  '/turbo.json',
  '/pnpm-workspace.yaml',
]);

const MARKERS = [
  '@generated',
  'generated by',
  'code generated',
  'do not edit',
  'do not modify',
  'auto-generated',
  'autogenerated',
  '<auto-generated',
  'this file was automatically generated',
];

export type WorkspaceHints = {
  /** True when nx.json, angular.json, workspace.json or turbo.json sits at the root. */
  monorepo: boolean;
};

export type ClassifyInput = {
  /** git attributes for this path, from `git check-attr`. */
  attributes?: ReadonlySet<string>;
  /** The first lines of the new side, for marker detection. Null when unavailable. */
  header?: string | null;
  workspace: WorkspaceHints;
  /** User globs; a `!` prefix forces a path back into the review. */
  patterns?: readonly string[];
  /** Paths the user has said are not scaffolding, remembered per repository. */
  overrides?: ReadonlySet<string>;
};

/**
 * Decide whether a file is generator output rather than review material.
 *
 * Signals are applied in order of trust, and every positive verdict carries a reason,
 * because a classifier that hides files without saying why is a classifier nobody trusts.
 * Precision beats recall throughout: misclassifying hand-written code costs a review,
 * missing one generated file costs nothing.
 */
export function classifyFile(file: FileChange, input: ClassifyInput): Verdict {
  const path = file.path;

  // 0. The user's word, first and last.
  if (input.overrides?.has(path)) return NOT;
  const { forced, exempt } = splitPatterns(input.patterns ?? []);
  if (exempt.matches(path)) return NOT;
  if (forced.matches(path)) return yes('matches a configured pattern');

  // 1. The repository has already said so.
  if (input.attributes?.has('linguist-generated')) return yes('marked linguist-generated');
  if (input.attributes?.has('no-diff')) return yes('marked -diff in .gitattributes');

  // 2. The file says so about itself.
  if (input.header && hasGeneratedMarker(input.header)) return yes('generated marker in the file');

  // 3. Generated or vendored by convention.
  if (VENDORED.matches(path)) return yes(lockfileReason(path));

  // 4. Workspace generator output, but only in a workspace that has generators.
  if (input.workspace.monorepo && WORKSPACE_CONFIG.matches(path) && !isRepoRoot(path)) {
    return yes('workspace project config');
  }

  return NOT;
}

/**
 * Classify a whole change set, then take one pass that needs the whole set to be safe.
 *
 * A generator also edits the root registries — `nx.json`, `tsconfig.base.json` — and so does
 * a person, all the time. Those are only scaffolding when the edit has a generator's
 * signature: small, additions only, and alongside output this pass already recognised.
 */
export function classifyAll(files: FileChange[], inputs: Map<string, ClassifyInput>): Map<string, Verdict> {
  const verdicts = new Map<string, Verdict>();
  let generated = 0;

  for (const file of files) {
    const input = inputs.get(file.path);
    const verdict = input ? classifyFile(file, input) : NOT;
    verdicts.set(file.path, verdict);
    if (verdict.scaffolding) generated += 1;
  }

  if (generated > 0) {
    for (const file of files) {
      if (verdicts.get(file.path)?.scaffolding) continue;
      if (!ROOT_REGISTRY.matches(file.path)) continue;
      if (inputs.get(file.path)?.overrides?.has(file.path)) continue;
      // A generator adds an entry; in pretty-printed JSON that also rewrites the line above
      // it to gain a comma. So the test is "small and net additive", not "additions only" —
      // which would never fire on the JSON these registries actually are.
      const { added, removed } = file.stats;
      if (added > removed && added <= 8 && removed <= 2) {
        verdicts.set(file.path, yes('registry entry added alongside generator output'));
      }
    }
  }

  return verdicts;
}

/** Apply verdicts to the hunks, which is where the rest of the review reads them. */
export function applyVerdicts(files: FileChange[], verdicts: Map<string, Verdict>): void {
  for (const file of files) {
    const verdict = verdicts.get(file.path);
    for (const hunk of file.hunks) {
      if (verdict?.scaffolding) hunk.scaffolding = { reason: verdict.reason };
      else delete hunk.scaffolding;
    }
  }
}

function hasGeneratedMarker(header: string): boolean {
  const text = header.slice(0, 2000).toLowerCase();
  return MARKERS.some((marker) => text.includes(marker));
}

function lockfileReason(path: string): string {
  if (/(^|\/)(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb)$/.test(path)) return 'lockfile';
  if (path.endsWith('.lock') || path.endsWith('.sum')) return 'lockfile';
  if (/(^|\/)(dist|build|out|coverage|node_modules|vendor|third_party)\//.test(path)) return 'build or vendored output';
  if (path.includes('__snapshots__/')) return 'test snapshot';
  return 'generated by convention';
}

function isRepoRoot(path: string): boolean {
  return !path.includes('/');
}

function splitPatterns(patterns: readonly string[]): { forced: GlobSet; exempt: GlobSet } {
  const forced: string[] = [];
  const exempt: string[] = [];
  for (const pattern of patterns) {
    if (pattern.startsWith('!')) exempt.push(pattern.slice(1));
    else forced.push(pattern);
  }
  return { forced: new GlobSet(forced), exempt: new GlobSet(exempt) };
}
