import type { FileChange } from '../git/parse.js';
import { GlobSet } from './glob.js';

export type Verdict = { scaffolding: false } | { scaffolding: true; reason: string };

const NOT: Verdict = { scaffolding: false };
const yes = (reason: string): Verdict => ({ scaffolding: true, reason });

/**
 * Paths that are generated or vendored by convention. Certain enough to act on without
 * looking inside the file.
 */
const VENDORED = new GlobSet([
  'package-lock.json',
  'pnpm-lock.yaml',
  'yarn.lock',
  'npm-shrinkwrap.json',
  'bun.lockb',
  'Cargo.lock',
  'poetry.lock',
  'Pipfile.lock',
  'composer.lock',
  'Gemfile.lock',
  'go.sum',
  '*.lock',
  'vendor/',
  'third_party/',
  'node_modules/',
  'dist/',
  'build/',
  'out/',
  '.angular/',
  '.next/',
  '.nuxt/',
  'coverage/',
  '__snapshots__/',
  '*.min.js',
  '*.min.css',
  '*.map',
  '*.pb.go',
  '*_pb2.py',
  '*.g.dart',
  '*.g.ts',
  '*.generated.ts',
  '*.generated.cs',
  '*.designer.cs',
]);

/**
 * Config files a workspace generator writes and then never asks a human to read. Only
 * treated as scaffolding when the repository actually is such a workspace.
 */
const WORKSPACE_CONFIG = new GlobSet([
  'project.json',
  'jest.config.ts',
  'jest.config.js',
  'jest.preset.js',
  'vite.config.ts',
  'vitest.config.ts',
  '.eslintrc.json',
  '.eslintrc.js',
  'eslint.config.js',
  '.babelrc',
  'tsconfig.json',
  'tsconfig.*.json',
  'karma.conf.js',
  '.browserslistrc',
]);

/** Root registries a generator edits — but so does a person, so these need corroboration. */
const ROOT_REGISTRY = new GlobSet([
  '/nx.json',
  '/tsconfig.base.json',
  '/angular.json',
  '/workspace.json',
  '/turbo.json',
  '/pnpm-workspace.yaml',
]);

const MARKERS = [
  '@generated',
  'generated by',
  'code generated',
  'do not edit',
  'do not modify',
  'auto-generated',
  'autogenerated',
  '<auto-generated',
  'this file was automatically generated',
];

export type WorkspaceHints = {
  /** True when nx.json, angular.json, workspace.json or turbo.json sits at the root. */
  monorepo: boolean;
};

/** Files a generator writes beside the code it scaffolds, by shape rather than by workspace. */
const GENERATED_SHAPE = new GlobSet([
  'project.json',
  'tsconfig.json',
  'tsconfig.*.json',
  'jest.config.*',
  'vite.config.*',
  'vitest.config.*',
  '.eslintrc.*',
  'eslint.config.*',
  '.babelrc',
  'karma.conf.js',
  '.browserslistrc',
  // Not README.md. A generator writes one, but so does the first person with something to
  // say about the library, and hiding documentation costs more than showing boilerplate.
]);

export type ClassifyInput = {
  /** git attributes for this path, from `git check-attr`. */
  attributes?: ReadonlySet<string>;
  /** The first lines of the new side, for marker detection. Null when unavailable. */
  header?: string | null;
  workspace: WorkspaceHints;
  /** User globs; a `!` prefix forces a path back into the review. */
  patterns?: readonly string[];
  /** Paths the user has said are not scaffolding, remembered per repository. */
  overrides?: ReadonlySet<string>;
};

/**
 * Decide whether a file is generator output rather than review material.
 *
 * Signals are applied in order of trust, and every positive verdict carries a reason,
 * because a classifier that hides files without saying why is a classifier nobody trusts.
 * Precision beats recall throughout: misclassifying hand-written code costs a review,
 * missing one generated file costs nothing.
 */
export function classifyFile(file: FileChange, input: ClassifyInput): Verdict {
  const path = file.path;

  // 0. The user's word, first and last.
  if (input.overrides?.has(path)) return NOT;
  const { forced, exempt } = splitPatterns(input.patterns ?? []);
  if (exempt.matches(path)) return NOT;
  if (forced.matches(path)) return yes('matches a configured pattern');

  // 1. The repository has already said so.
  if (input.attributes?.has('linguist-generated')) return yes('marked linguist-generated');
  if (input.attributes?.has('no-diff')) return yes('marked -diff in .gitattributes');

  // 2. The file says so about itself.
  if (input.header && hasGeneratedMarker(input.header)) return yes('generated marker in the file');

  // 3. Generated or vendored by convention.
  if (VENDORED.matches(path)) return yes(lockfileReason(path));

  // 4. Workspace generator output, but only in a workspace that has generators.
  if (input.workspace.monorepo && WORKSPACE_CONFIG.matches(path) && !isRepoRoot(path)) {
    return yes('workspace project config');
  }

  // 6. The shape of the content, last and weakest. A file that is all additions, large, and
  // barely repeats itself in the way only a machine writes.
  const shape = machineWritten(file);
  if (shape) return yes(shape);

  return NOT;
}

/**
 * Catch the generated artefact nobody thought to name.
 *
 * Deliberately hard to trigger: every test here has to hold at once, and the thresholds are
 * set where hand-written code does not go. A false positive hides real code, which is the
 * one failure of this whole feature that matters.
 */
function machineWritten(file: FileChange): string | null {
  if (file.status !== 'added' && file.stats.removed > 0) return null;

  const added: string[] = [];
  for (const hunk of file.hunks) {
    if (hunk.kind !== 'text') return null;
    for (const line of hunk.lines) {
      if (line.startsWith('+')) added.push(line.slice(1));
    }
  }
  if (added.length < 200) return null;

  const longest = added.reduce((n, line) => Math.max(n, line.length), 0);
  if (longest > 2000) return 'a line no one would write by hand';

  const distinct = new Set(added.map((line) => line.trim())).size;
  if (distinct / added.length < 0.15) return 'repeats itself the way generated data does';

  return null;
}

/**
 * Classify a whole change set, then take one pass that needs the whole set to be safe.
 *
 * A generator also edits the root registries — `nx.json`, `tsconfig.base.json` — and so does
 * a person, all the time. Those are only scaffolding when the edit has a generator's
 * signature: small, additions only, and alongside output this pass already recognised.
 */
export function classifyAll(files: FileChange[], inputs: Map<string, ClassifyInput>): Map<string, Verdict> {
  const verdicts = new Map<string, Verdict>();
  let generated = 0;

  for (const file of files) {
    const input = inputs.get(file.path);
    const verdict = input ? classifyFile(file, input) : NOT;
    verdicts.set(file.path, verdict);
    if (verdict.scaffolding) generated += 1;
  }

  // 5. Scaffold shape: a directory that did not exist before, arriving whole. A generated
  // library is recognisable by its silhouette even when no single file is suspicious — but
  // only its config files are claimed. The code inside a new library is exactly what the
  // reviewer is there to read.
  const byDirectory = new Map<string, FileChange[]>();
  for (const file of files) {
    if (file.status !== 'added') continue;
    const at = file.path.lastIndexOf('/');
    if (at === -1) continue;
    const dir = file.path.slice(0, at);
    byDirectory.set(dir, [...(byDirectory.get(dir) ?? []), file]);
  }

  for (const [, siblings] of byDirectory) {
    const shaped = siblings.filter((file) => GENERATED_SHAPE.matches(file.path));
    // Two config files arriving together with other new files is a generator's signature;
    // one is somebody adding a config file.
    if (shaped.length < 2 || siblings.length < 3) continue;

    for (const file of shaped) {
      if (verdicts.get(file.path)?.scaffolding) continue;
      if (inputs.get(file.path)?.overrides?.has(file.path)) continue;
      verdicts.set(file.path, yes('config a generator wrote with the rest of this directory'));
      generated += 1;
    }
  }

  if (generated > 0) {
    for (const file of files) {
      if (verdicts.get(file.path)?.scaffolding) continue;
      if (!ROOT_REGISTRY.matches(file.path)) continue;
      if (inputs.get(file.path)?.overrides?.has(file.path)) continue;
      // A generator adds an entry; in pretty-printed JSON that also rewrites the line above
      // it to gain a comma. So the test is "small and net additive", not "additions only" —
      // which would never fire on the JSON these registries actually are.
      const { added, removed } = file.stats;
      if (added > removed && added <= 8 && removed <= 2) {
        verdicts.set(file.path, yes('registry entry added alongside generator output'));
      }
    }
  }

  return verdicts;
}

/** Apply verdicts to the hunks, which is where the rest of the review reads them. */
export function applyVerdicts(files: FileChange[], verdicts: Map<string, Verdict>): void {
  for (const file of files) {
    const verdict = verdicts.get(file.path);
    for (const hunk of file.hunks) {
      if (verdict?.scaffolding) hunk.scaffolding = { reason: verdict.reason };
      else delete hunk.scaffolding;
    }
  }
}

function hasGeneratedMarker(header: string): boolean {
  const text = header.slice(0, 2000).toLowerCase();
  return MARKERS.some((marker) => text.includes(marker));
}

function lockfileReason(path: string): string {
  if (/(^|\/)(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb)$/.test(path)) return 'lockfile';
  if (path.endsWith('.lock') || path.endsWith('.sum')) return 'lockfile';
  if (/(^|\/)(dist|build|out|coverage|node_modules|vendor|third_party)\//.test(path)) return 'build or vendored output';
  if (path.includes('__snapshots__/')) return 'test snapshot';
  return 'generated by convention';
}

function isRepoRoot(path: string): boolean {
  return !path.includes('/');
}

function splitPatterns(patterns: readonly string[]): { forced: GlobSet; exempt: GlobSet } {
  const forced: string[] = [];
  const exempt: string[] = [];
  for (const pattern of patterns) {
    if (pattern.startsWith('!')) exempt.push(pattern.slice(1));
    else forced.push(pattern);
  }
  return { forced: new GlobSet(forced), exempt: new GlobSet(exempt) };
}
