import { describe, expect, it } from 'vitest';
import { classifyAll, classifyFile, applyVerdicts, type ClassifyInput } from '../../src/model/noise.js';
import { globToRegExp } from '../../src/model/glob.js';
import type { FileChange } from '../../src/git/parse.js';

const file = (path: string, over: Partial<FileChange> = {}): FileChange => ({
  path,
  status: 'modified',
  binary: false,
  hunks: [
    {
      id: 'h',
      path,
      oldStart: 1,
      oldCount: 1,
      newStart: 1,
      newCount: 1,
      lines: ['+x'],
      stats: { added: 1, removed: 0 },
      kind: 'text',
    },
  ],
  stats: { added: 1, removed: 0 },
  ...over,
});

const plain: ClassifyInput = { workspace: { monorepo: false } };
const monorepo: ClassifyInput = { workspace: { monorepo: true } };

describe('globToRegExp', () => {
  it('matches a bare name anywhere', () => {
    expect(globToRegExp('yarn.lock').test('apps/web/yarn.lock')).toBe(true);
  });

  it('does not let * cross a separator', () => {
    expect(globToRegExp('src/*.ts').test('src/deep/a.ts')).toBe(false);
    expect(globToRegExp('src/*.ts').test('src/a.ts')).toBe(true);
  });

  it('lets **/ match nothing as well as many segments', () => {
    const re = globToRegExp('**/__snapshots__/');
    expect(re.test('__snapshots__/a.snap')).toBe(true);
    expect(re.test('a/b/__snapshots__/c.snap')).toBe(true);
  });

  it('anchors a leading slash to the root', () => {
    expect(globToRegExp('/nx.json').test('nx.json')).toBe(true);
    expect(globToRegExp('/nx.json').test('apps/nx.json')).toBe(false);
  });

  it('matches a directory pattern and everything under it', () => {
    const re = globToRegExp('dist/');
    expect(re.test('dist')).toBe(true);
    expect(re.test('dist/main.js')).toBe(true);
    expect(re.test('distant/main.js')).toBe(false);
  });
});

describe('classifyFile', () => {
  it('trusts .gitattributes over everything else', () => {
    const verdict = classifyFile(file('src/api.ts'), {
      ...plain,
      attributes: new Set(['linguist-generated']),
    });
    expect(verdict).toEqual({ scaffolding: true, reason: 'marked linguist-generated' });
  });

  it('reads a generated marker in the file', () => {
    const verdict = classifyFile(file('src/api.ts'), {
      ...plain,
      header: '// Code generated by protoc-gen-go. DO NOT EDIT.\n',
    });
    expect(verdict).toMatchObject({ scaffolding: true, reason: 'generated marker in the file' });
  });

  it('classifies lockfiles', () => {
    expect(classifyFile(file('pnpm-lock.yaml'), plain)).toMatchObject({ reason: 'lockfile' });
    expect(classifyFile(file('go.sum'), plain)).toMatchObject({ reason: 'lockfile' });
  });

  it('classifies build output and vendored trees', () => {
    expect(classifyFile(file('dist/main.js'), plain).scaffolding).toBe(true);
    expect(classifyFile(file('vendor/lib/x.go'), plain).scaffolding).toBe(true);
  });

  it('treats workspace project config as scaffolding only in a workspace', () => {
    expect(classifyFile(file('libs/auth/project.json'), monorepo).scaffolding).toBe(true);
    expect(classifyFile(file('libs/auth/project.json'), plain).scaffolding).toBe(false);
  });

  it('leaves a root config alone even in a workspace, since a person edits it', () => {
    expect(classifyFile(file('tsconfig.json'), monorepo).scaffolding).toBe(false);
  });

  it('never classifies ordinary source', () => {
    for (const path of ['src/auth/token.ts', 'lib/parser.rs', 'app/views/home.tsx', 'README.md']) {
      expect(classifyFile(file(path), monorepo).scaffolding).toBe(false);
    }
  });

  it('obeys a user pattern, and a ! pattern beats it', () => {
    expect(classifyFile(file('src/schema.ts'), { ...plain, patterns: ['src/schema.ts'] }).scaffolding).toBe(true);
    expect(
      classifyFile(file('libs/a/project.json'), { ...monorepo, patterns: ['!**/project.json'] }).scaffolding,
    ).toBe(false);
  });

  it('obeys a remembered "not scaffolding" override above every signal', () => {
    const verdict = classifyFile(file('pnpm-lock.yaml'), {
      ...plain,
      overrides: new Set(['pnpm-lock.yaml']),
    });
    expect(verdict.scaffolding).toBe(false);
  });
});

describe('classifyAll', () => {
  const inputs = (paths: string[], input: ClassifyInput) => new Map(paths.map((p) => [p, input]));

  it('claims a small additive root-registry edit that sits beside generator output', () => {
    const files = [
      file('libs/auth/project.json'),
      file('nx.json', { stats: { added: 3, removed: 0 } }),
    ];
    const verdicts = classifyAll(files, inputs(['libs/auth/project.json', 'nx.json'], monorepo));
    expect(verdicts.get('nx.json')).toMatchObject({ scaffolding: true });
  });

  it('leaves the same registry alone when nothing else was generated', () => {
    const files = [file('nx.json', { stats: { added: 3, removed: 0 } })];
    const verdicts = classifyAll(files, inputs(['nx.json'], monorepo));
    expect(verdicts.get('nx.json')!.scaffolding).toBe(false);
  });

  it('tolerates the comma a generator rewrites, but not a real edit', () => {
    const beside = ['libs/a/project.json', 'nx.json'];
    const comma = [file('libs/a/project.json'), file('nx.json', { stats: { added: 3, removed: 1 } })];
    expect(classifyAll(comma, inputs(beside, monorepo)).get('nx.json')!.scaffolding).toBe(true);

    const rewrite = [file('libs/a/project.json'), file('nx.json', { stats: { added: 3, removed: 5 } })];
    expect(classifyAll(rewrite, inputs(beside, monorepo)).get('nx.json')!.scaffolding).toBe(false);
  });

  it('leaves a large registry edit alone, however much else was generated', () => {
    const files = [file('libs/a/project.json'), file('nx.json', { stats: { added: 40, removed: 0 } })];
    const verdicts = classifyAll(files, inputs(['libs/a/project.json', 'nx.json'], monorepo));
    expect(verdicts.get('nx.json')!.scaffolding).toBe(false);
  });
});

describe('applyVerdicts', () => {
  it('puts the reason on every hunk of the file, and clears a stale one', () => {
    const files = [file('dist/a.js')];
    applyVerdicts(files, classifyAll(files, new Map([['dist/a.js', plain]])));
    expect(files[0]!.hunks[0]!.scaffolding).toEqual({ reason: 'build or vendored output' });

    applyVerdicts(files, new Map());
    expect(files[0]!.hunks[0]!.scaffolding).toBeUndefined();
  });
});
