import { describe, expect, it } from 'vitest';
import { classifyAll, classifyFile, applyVerdicts, type ClassifyInput } from '../../src/model/noise.js';
import { globToRegExp } from '../../src/model/glob.js';
import type { FileChange } from '../../src/git/parse.js';

const file = (path: string, over: Partial<FileChange> = {}): FileChange => ({
  path,
  status: 'modified',
  binary: false,
  hunks: [
    {
      id: 'h',
      path,
      oldStart: 1,
      oldCount: 1,
      newStart: 1,
      newCount: 1,
      lines: ['+x'],
      stats: { added: 1, removed: 0 },
      kind: 'text',
    },
  ],
  stats: { added: 1, removed: 0 },
  ...over,
});

const plain: ClassifyInput = { workspace: { monorepo: false } };
const monorepo: ClassifyInput = { workspace: { monorepo: true } };

describe('globToRegExp', () => {
  it('matches a bare name anywhere', () => {
    expect(globToRegExp('yarn.lock').test('apps/web/yarn.lock')).toBe(true);
  });

  it('does not let * cross a separator', () => {
    expect(globToRegExp('src/*.ts').test('src/deep/a.ts')).toBe(false);
    expect(globToRegExp('src/*.ts').test('src/a.ts')).toBe(true);
  });

  it('lets **/ match nothing as well as many segments', () => {
    const re = globToRegExp('**/__snapshots__/');
    expect(re.test('__snapshots__/a.snap')).toBe(true);
    expect(re.test('a/b/__snapshots__/c.snap')).toBe(true);
  });

  it('anchors a leading slash to the root', () => {
    expect(globToRegExp('/nx.json').test('nx.json')).toBe(true);
    expect(globToRegExp('/nx.json').test('apps/nx.json')).toBe(false);
  });

  it('matches a directory pattern and everything under it', () => {
    const re = globToRegExp('dist/');
    expect(re.test('dist')).toBe(true);
    expect(re.test('dist/main.js')).toBe(true);
    expect(re.test('distant/main.js')).toBe(false);
  });
});

describe('classifyFile', () => {
  it('trusts .gitattributes over everything else', () => {
    const verdict = classifyFile(file('src/api.ts'), {
      ...plain,
      attributes: new Set(['linguist-generated']),
    });
    expect(verdict).toEqual({ scaffolding: true, reason: 'marked linguist-generated' });
  });

  it('reads a generated marker in the file', () => {
    const verdict = classifyFile(file('src/api.ts'), {
      ...plain,
      header: '// Code generated by protoc-gen-go. DO NOT EDIT.\n',
    });
    expect(verdict).toMatchObject({ scaffolding: true, reason: 'generated marker in the file' });
  });

  it('classifies lockfiles', () => {
    expect(classifyFile(file('pnpm-lock.yaml'), plain)).toMatchObject({ reason: 'lockfile' });
    expect(classifyFile(file('go.sum'), plain)).toMatchObject({ reason: 'lockfile' });
  });

  it('classifies build output and vendored trees', () => {
    expect(classifyFile(file('dist/main.js'), plain).scaffolding).toBe(true);
    expect(classifyFile(file('vendor/lib/x.go'), plain).scaffolding).toBe(true);
  });

  it('treats workspace project config as scaffolding only in a workspace', () => {
    expect(classifyFile(file('libs/auth/project.json'), monorepo).scaffolding).toBe(true);
    expect(classifyFile(file('libs/auth/project.json'), plain).scaffolding).toBe(false);
  });

  it('leaves a root config alone even in a workspace, since a person edits it', () => {
    expect(classifyFile(file('tsconfig.json'), monorepo).scaffolding).toBe(false);
  });

  it('never classifies ordinary source', () => {
    for (const path of ['src/auth/token.ts', 'lib/parser.rs', 'app/views/home.tsx', 'README.md']) {
      expect(classifyFile(file(path), monorepo).scaffolding).toBe(false);
    }
  });

  it('obeys a user pattern, and a ! pattern beats it', () => {
    expect(classifyFile(file('src/schema.ts'), { ...plain, patterns: ['src/schema.ts'] }).scaffolding).toBe(true);
    expect(
      classifyFile(file('libs/a/project.json'), { ...monorepo, patterns: ['!**/project.json'] }).scaffolding,
    ).toBe(false);
  });

  it('obeys a remembered "not scaffolding" override above every signal', () => {
    const verdict = classifyFile(file('pnpm-lock.yaml'), {
      ...plain,
      overrides: new Set(['pnpm-lock.yaml']),
    });
    expect(verdict.scaffolding).toBe(false);
  });
});

describe('the shape of the content', () => {
  const generated = (path: string, lines: string[]): FileChange => {
    const f = file(path, { status: 'added' });
    f.hunks[0]!.lines = lines.map((line) => `+${line}`);
    f.stats = { added: lines.length, removed: 0 };
    return f;
  };

  it('catches a large file that repeats itself the way generated data does', () => {
    const rows = Array.from({ length: 400 }, (_, i) => (i % 20 === 0 ? `  unique ${i}` : '  "value": 1,'));
    expect(classifyFile(generated('src/data.ts', rows), plain)).toMatchObject({
      scaffolding: true,
      reason: 'repeats itself the way generated data does',
    });
  });

  it('catches a line no one would write by hand', () => {
    const rows = Array.from({ length: 250 }, (_, i) => `const x${i} = ${i};`);
    rows[0] = 'a'.repeat(3000);
    expect(classifyFile(generated('src/bundle.ts', rows), plain).scaffolding).toBe(true);
  });

  it('leaves a large hand-written file alone', () => {
    const rows = Array.from({ length: 400 }, (_, i) => `export function handler${i}(request: Request) {`);
    expect(classifyFile(generated('src/routes.ts', rows), plain).scaffolding).toBe(false);
  });

  it('leaves a small repetitive file alone, since size is half the signal', () => {
    const rows = Array.from({ length: 60 }, () => '  "value": 1,');
    expect(classifyFile(generated('src/small.ts', rows), plain).scaffolding).toBe(false);
  });

  it('never claims a file that had anything removed', () => {
    const rows = Array.from({ length: 400 }, () => '  "value": 1,');
    const edited = generated('src/data.ts', rows);
    edited.status = 'modified';
    edited.stats = { added: 400, removed: 3 };
    expect(classifyFile(edited, plain).scaffolding).toBe(false);
  });
});

describe('a new document with nothing in it', () => {
  const doc = (path: string, body: string): FileChange => {
    const lines = body.split('\n');
    const f = file(path, { status: 'added' });
    f.hunks[0]!.lines = lines.map((line) => `+${line}`);
    f.stats = { added: lines.length, removed: 0 };
    return f;
  };

  it('hides a README that is a heading and a metadata table', () => {
    const verdict = classifyFile(
      doc('libs/payments/types/README.md', '# payments\n\n**Type:** types\n\n## Tags\n\ntype:types, scope:server\n'),
      plain,
    );
    expect(verdict).toMatchObject({
      scaffolding: true,
      reason: 'a heading and metadata, with nothing written under them',
    });
  });

  it('hides one that is nothing but a title', () => {
    expect(classifyFile(doc('libs/auth/types/README.md', '# auth\n'), plain).scaffolding).toBe(true);
  });

  it('keeps one the moment somebody writes a sentence in it', () => {
    const verdict = classifyFile(
      doc('libs/auth/core/README.md', '# auth\n\n**Type:** core\n\n## Description\n\nAuth library for core functionality.\n'),
      plain,
    );
    expect(verdict.scaffolding).toBe(false);
  });

  it('counts a usage example as something worth reading', () => {
    const verdict = classifyFile(
      doc('libs/x/README.md', '# x\n\n## Usage\n\n```ts\nimport { X } from "@x";\n```\n'),
      plain,
    );
    expect(verdict.scaffolding).toBe(false);
  });

  it('keeps even a TODO, because a note is not nothing', () => {
    expect(classifyFile(doc('docs/scss/README.md', '# Best practices\n\nTODO: add\n'), plain).scaffolding).toBe(
      false,
    );
  });

  it('never touches a README somebody edited', () => {
    const edited = doc('libs/x/README.md', '# x\n\n**Type:** ui\n');
    edited.status = 'modified';
    // In a modified file the diff carries the new lines, not the document: an empty-looking
    // change may be one line added to something substantial.
    expect(classifyFile(edited, plain).scaffolding).toBe(false);
  });

  it('leaves code alone, however terse', () => {
    expect(classifyFile(doc('src/index.ts', 'export {};\n'), plain).scaffolding).toBe(false);
  });
});

describe('the shape of a scaffolded directory', () => {
  const added = (path: string) => file(path, { status: 'added' });
  const inputsFor = (files: FileChange[]) =>
    new Map(files.map((f) => [f.path, plain] as const));

  it('claims the config a generator wrote, and not the code beside it', () => {
    const files = [
      added('libs/tokens/project.json'),
      added('libs/tokens/tsconfig.lib.json'),
      added('libs/tokens/jest.config.ts'),
      added('libs/tokens/src/index.ts'),
    ];
    const verdicts = classifyAll(files, inputsFor(files));

    expect(verdicts.get('libs/tokens/project.json')!.scaffolding).toBe(true);
    expect(verdicts.get('libs/tokens/jest.config.ts')!.scaffolding).toBe(true);
    // The code inside a new library is exactly what the reviewer is there to read.
    expect(verdicts.get('libs/tokens/src/index.ts')!.scaffolding).toBe(false);
  });

  it('does not fire on one config file added by a person', () => {
    const files = [added('src/feature/tsconfig.json'), added('src/feature/index.ts'), added('src/feature/a.ts')];
    const verdicts = classifyAll(files, inputsFor(files));
    expect(verdicts.get('src/feature/tsconfig.json')!.scaffolding).toBe(false);
  });

  it('leaves a new library\'s README alone, boilerplate or not', () => {
    const files = [
      added('libs/x/project.json'),
      added('libs/x/tsconfig.lib.json'),
      added('libs/x/README.md'),
      added('libs/x/src/index.ts'),
    ];
    const verdicts = classifyAll(files, inputsFor(files));
    expect(verdicts.get('libs/x/README.md')!.scaffolding).toBe(false);
  });

  it('does not fire on a directory with nothing but config in it', () => {
    const files = [added('config/tsconfig.json'), added('config/.eslintrc.json')];
    const verdicts = classifyAll(files, inputsFor(files));
    expect(verdicts.get('config/tsconfig.json')!.scaffolding).toBe(false);
  });

  it('still obeys a reviewer who says otherwise', () => {
    const files = [
      added('libs/x/project.json'),
      added('libs/x/tsconfig.lib.json'),
      added('libs/x/src/index.ts'),
    ];
    const inputs = new Map(
      files.map((f) => [f.path, { ...plain, overrides: new Set(['libs/x/project.json']) }] as const),
    );
    expect(classifyAll(files, inputs).get('libs/x/project.json')!.scaffolding).toBe(false);
  });
});

describe('classifyAll', () => {
  const inputs = (paths: string[], input: ClassifyInput) => new Map(paths.map((p) => [p, input]));

  it('claims a small additive root-registry edit that sits beside generator output', () => {
    const files = [
      file('libs/auth/project.json'),
      file('nx.json', { stats: { added: 3, removed: 0 } }),
    ];
    const verdicts = classifyAll(files, inputs(['libs/auth/project.json', 'nx.json'], monorepo));
    expect(verdicts.get('nx.json')).toMatchObject({ scaffolding: true });
  });

  it('leaves the same registry alone when nothing else was generated', () => {
    const files = [file('nx.json', { stats: { added: 3, removed: 0 } })];
    const verdicts = classifyAll(files, inputs(['nx.json'], monorepo));
    expect(verdicts.get('nx.json')!.scaffolding).toBe(false);
  });

  it('tolerates the comma a generator rewrites, but not a real edit', () => {
    const beside = ['libs/a/project.json', 'nx.json'];
    const comma = [file('libs/a/project.json'), file('nx.json', { stats: { added: 3, removed: 1 } })];
    expect(classifyAll(comma, inputs(beside, monorepo)).get('nx.json')!.scaffolding).toBe(true);

    const rewrite = [file('libs/a/project.json'), file('nx.json', { stats: { added: 3, removed: 5 } })];
    expect(classifyAll(rewrite, inputs(beside, monorepo)).get('nx.json')!.scaffolding).toBe(false);
  });

  it('leaves a large registry edit alone, however much else was generated', () => {
    const files = [file('libs/a/project.json'), file('nx.json', { stats: { added: 40, removed: 0 } })];
    const verdicts = classifyAll(files, inputs(['libs/a/project.json', 'nx.json'], monorepo));
    expect(verdicts.get('nx.json')!.scaffolding).toBe(false);
  });
});

describe('applyVerdicts', () => {
  it('puts the reason on every hunk of the file, and clears a stale one', () => {
    const files = [file('dist/a.js')];
    applyVerdicts(files, classifyAll(files, new Map([['dist/a.js', plain]])));
    expect(files[0]!.hunks[0]!.scaffolding).toEqual({ reason: 'build or vendored output' });

    applyVerdicts(files, new Map());
    expect(files[0]!.hunks[0]!.scaffolding).toBeUndefined();
  });
});
